import React, { useEffect, useState, useCallback } from 'react';
import { useApp } from '../context/AppContext';
import { db, newId, nowISO } from '../lib/db';
import { FileText, Download, Copy, Eye, Plus } from 'lucide-react';

const REPORT_TYPES = ['hackerone','bugcrowd','pentest','generic'];

function generateHackerOneReport(finding: any, project: any): string {
  return `# ${finding.title}

## Summary

${finding.summary || 'A security vulnerability was identified during authorized testing of the application.'}

## Asset

${finding.asset || project?.name || 'See details below'}

## Vulnerability Type

${finding.owasp_category || 'See CWE below'}  
**CWE:** ${finding.cwe || 'N/A'}  
**CVSS Score:** ${finding.cvss_score || 'N/A'} ${finding.cvss_vector ? `(${finding.cvss_vector})` : ''}

## Preconditions

${finding.prerequisites || 'Authenticated user session required.' }

## Steps to Reproduce

${finding.steps || '1. [Step 1]\n2. [Step 2]\n3. [Step 3]'}

## Proof of Concept

[Attach screenshots and request/response evidence]

## Observed Result

${finding.observed_result || 'See evidence attached.'}

## Expected Result

${finding.expected_result || 'The application should properly enforce authorization controls.'}

## Impact

**Technical Impact:** ${finding.impact || 'See description.'}

**Business Impact:** ${finding.business_impact || 'Potential for unauthorized access to sensitive data or functionality.'}

## Suggested Severity

**${(finding.severity || 'medium').toUpperCase()}**

## Remediation

${finding.remediation || 'Implement proper server-side authorization checks for all sensitive operations.'}

## Supporting Information

- **Tested by:** Sachin
- **Project:** ${project?.name || 'N/A'}
- **Date:** ${new Date().toLocaleDateString()}
- **Testing conducted on researcher-controlled accounts and data only.**

---
*Report generated by BountyScope Ultimate*
`;
}

function generatePentestReport(finding: any, project: any): string {
  return `# Penetration Test Finding Report

**Project:** ${project?.name || 'N/A'}  
**Date:** ${new Date().toLocaleDateString()}  
**Researcher:** Sachin  
**Severity:** ${(finding.severity || 'medium').toUpperCase()}  
**Status:** ${finding.status || 'validated'}

---

## Finding: ${finding.title}

### Description

${finding.summary || 'A security vulnerability was identified.'}

### CVSS

**Score:** ${finding.cvss_score || 'N/A'}  
**Vector:** ${finding.cvss_vector || 'N/A'}

### Affected Asset

${finding.asset || 'N/A'}

### Affected Parameter

${finding.affected_parameter || 'N/A'}

### Prerequisites

${finding.prerequisites || 'N/A'}

### Steps to Reproduce

${finding.steps || 'N/A'}

### Evidence

${finding.observed_result || 'See attached screenshots.'}

### Expected Behavior

${finding.expected_result || 'N/A'}

### Risk / Impact

${finding.impact || 'N/A'}

**Business Impact:** ${finding.business_impact || 'N/A'}

### Remediation Guidance

${finding.remediation || 'N/A'}

### References

${finding.references || 'N/A'}

---
*Generated by BountyScope Ultimate · Developed by Sachin*
`;
}

export default function Reports() {
  const { activeProject } = useApp();
  const [findings, setFindings] = useState<any[]>([]);
  const [selectedFindingId, setSelectedFindingId] = useState('');
  const [reportType, setReportType] = useState('hackerone');
  const [reportContent, setReportContent] = useState('');
  const [showPreview, setShowPreview] = useState(false);

  const load = useCallback(async () => {
    if (!activeProject) { setFindings([]); return; }
    const res = await db.all('SELECT * FROM findings WHERE project_id=? ORDER BY severity DESC', [activeProject.id]);
    if (res.success) setFindings(res.result);
  }, [activeProject]);

  useEffect(() => { load(); }, [load]);

  const generate = () => {
    const finding = findings.find(f => f.id === selectedFindingId) || findings[0];
    if (!finding) { setReportContent('# No finding selected\n\nPlease select a finding from the dropdown.'); return; }
    let content = '';
    if (reportType === 'hackerone' || reportType === 'bugcrowd' || reportType === 'generic') {
      content = generateHackerOneReport(finding, activeProject);
    } else {
      content = generatePentestReport(finding, activeProject);
    }
    setReportContent(content);
  };

  const exportReport = async () => {
    if (!reportContent) return;
    const ext = 'md';
    const filename = `finding-report-${Date.now()}.${ext}`;
    const api = (window as any).electronAPI;
    if (api) {
      await api.fileSave({ defaultPath: filename, content: reportContent, filters: [{ name: 'Markdown', extensions: ['md'] }] });
    } else {
      const blob = new Blob([reportContent], { type: 'text/markdown' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a'); a.href = url; a.download = filename; a.click();
    }
  };

  const exportAllJson = async () => {
    const content = JSON.stringify(findings, null, 2);
    const api = (window as any).electronAPI;
    if (api) {
      await api.fileSave({ defaultPath: 'findings-export.json', content, filters: [{ name: 'JSON', extensions: ['json'] }] });
    }
  };

  return (
    <div className="page">
      <div className="page-header">
        <div><div className="page-title">Reports</div><div className="page-subtitle">Generate and export professional security reports</div></div>
        <div style={{ display: 'flex', gap: 8 }}>
          <button className="btn btn-secondary btn-sm" onClick={exportAllJson}><Download size={13}/> Export All Findings (JSON)</button>
        </div>
      </div>
      <div style={{ flex: 1, display: 'flex', overflow: 'hidden', minHeight: 0 }}>
        {/* Config panel */}
        <div style={{ width: 280, borderRight: '1px solid var(--border)', display: 'flex', flexDirection: 'column', padding: 16, gap: 12, overflow: 'auto' }}>
          <div>
            <div className="label">Report Type</div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
              {REPORT_TYPES.map(t => (
                <button key={t} className={`btn btn-sm ${reportType===t?'btn-primary':'btn-secondary'}`} style={{ justifyContent: 'flex-start' }} onClick={() => setReportType(t)}>
                  {t === 'hackerone' ? 'HackerOne Markdown' : t === 'bugcrowd' ? 'Bugcrowd Markdown' : t === 'pentest' ? 'Pentest Report' : 'Generic Disclosure'}
                </button>
              ))}
            </div>
          </div>
          <div>
            <div className="label">Finding</div>
            <select className="input select" value={selectedFindingId} onChange={e => setSelectedFindingId(e.target.value)}>
              <option value="">Select finding…</option>
              {findings.map(f => <option key={f.id} value={f.id}>[{f.severity}] {f.title}</option>)}
            </select>
          </div>
          <button className="btn btn-primary" onClick={generate}><FileText size={14}/> Generate Report</button>
          {reportContent && (
            <>
              <div className="divider" />
              <button className="btn btn-secondary" onClick={() => navigator.clipboard.writeText(reportContent)}><Copy size={13}/> Copy</button>
              <button className="btn btn-secondary" onClick={exportReport}><Download size={13}/> Export .md</button>
              <button className="btn btn-secondary" onClick={() => setShowPreview(p => !p)}><Eye size={13}/> {showPreview ? 'Hide' : 'Show'} Preview</button>
            </>
          )}

          {findings.length === 0 && (
            <div style={{ fontSize: '0.82rem', color: 'var(--text-muted)', padding: '12px 0' }}>
              No findings yet. Create findings first in the Findings module.
            </div>
          )}
        </div>

        {/* Report preview */}
        <div style={{ flex: 1, overflow: 'auto', padding: 24, display: 'flex', flexDirection: 'column', gap: 16 }}>
          {!reportContent ? (
            <div className="empty-state"><FileText size={40}/><h3>No Report Generated</h3><p>Select a finding and report type, then click Generate Report.</p></div>
          ) : (
            <div>
              <div style={{ display: 'flex', gap: 8, marginBottom: 16 }}>
                <span className="badge badge-cyan">{reportType}</span>
                {selectedFindingId && <span className="badge badge-muted">{findings.find(f=>f.id===selectedFindingId)?.title || ''}</span>}
              </div>
              <pre className="code-block select-text" style={{ fontSize: '0.82rem', whiteSpace: 'pre-wrap', lineHeight: 1.7 }}>{reportContent}</pre>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
